steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['submodule', 'update', '--init', '--recursive']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', 'docker/Dockerfile.abci', '-t', 'gcr.io/chainpoint-registry/$REPO_NAME/go-abci-service:$COMMIT_SHA', '-t', 'gcr.io/chainpoint-registry/$REPO_NAME/go-abci-service:latest', '.' ]
timeout: 1000s
images:
- 'gcr.io/chainpoint-registry/$REPO_NAME/go-abci-service:latest'
- 'gcr.io/chainpoint-registry/$REPO_NAME/go-abci-service:$COMMIT_SHA'
options:
 machineType: 'N1_HIGHCPU_8'
