version: '2.1'

networks:
  chainpoint:
    driver: bridge

services:

  abci:
    build:
      context: .
      dockerfile: docker/Dockerfile.abci
    image: abci
    depends_on:
    - rabbitmq
    environment:
      TENDERMINT_HOST: tendermint
      TENDERMINT_PORT: 26657
      ANCHOR: "true"
      AGGREGATE: "true"
    ports:
    - "26658"
    command: bash -c "abci-service"
    networks:
    - chainpoint

  tendermint:
    depends_on:
    - abci
    image: tierion/tendermint-cleveldb
    entrypoint: ''
    volumes:
    - ./config/node_1:/tendermint/config:Z
    - ./config/node_1/data:/tendermint/data:Z
    command: sh -c "tendermint node --p2p.persistent_peers a9767c6b5dc36192d81d911aa4381955b80fd784@tendermint-2:26656,e5195303cb2150c38c1e429f90f898c0edb143f4@127.0.0.1:26656 --moniker=`hostname` --proxy_app=abci:26658"
    ports:
    - "26656"
    - "26657:26657"
    networks:
    - chainpoint

  abci-2:
    build:
      context: .
      dockerfile: docker/Dockerfile.abci
    image: abci
    depends_on:
    - rabbitmq
    environment:
      TENDERMINT_HOST: tendermint-2
      TENDERMINT_PORT: 26657
    ports:
    - "26658"
    command: bash -c "abci-service"
    networks:
    - chainpoint

  tendermint-2:
    depends_on:
    - abci
    image: tierion/tendermint-cleveldb
    entrypoint: ''
    volumes:
    - ./config/node_2:/tendermint/config:Z
    - ./config/node_2/data:/tendermint/data:Z
    command: sh -c "tendermint node --p2p.persistent_peers a9767c6b5dc36192d81d911aa4381955b80fd784@127.0.0.1:26656,e5195303cb2150c38c1e429f90f898c0edb143f4@tendermint:26656 --moniker=`hostname` --proxy_app=abci-2:26658"
    ports:
    - "26656"
    - "26657"
    networks:
    - chainpoint

  # NGINX Proxy
  #
  # An auto-scaling reverse proxy that reconfigures
  # itself based on which API services are available
  # for requests.
  #
  # See : https://github.com/jwilder/nginx-proxy
  #
  # SCALED : false
  #
  # PORTS:
  # http : 80
  #
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy-core
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      NODE_ENV: development
      DEFAULT_HOST: api.local
    depends_on:
      - api
    networks:
      - chainpoint

  # Node.js Base Image
  # See : https://stackoverflow.com/questions/37933204/building-common-dependencies-with-docker-compose
  #
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile.node-base

  # HTTP API
  # Restify Node public web API service.
  #
  # Note : You don't access this directly, but through
  # the nginx-proxy load balancer. This service cannot be
  # given an explicit container_name since it needs
  # to be scalable with 'docker-compose scale api=5'
  #
  # The VIRTUAL_HOST env var is used by the nginx-proxy
  # to rebuild its reverse proxy host config and must be
  # passed in by the HTTP client:
  #
  # Start With:
  # docker-compose up -d --build nginx-proxy
  #
  # curl -i http://127.0.0.1/
  #
  # PORTS : 8080
  #
  api:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    depends_on:
      - base
      - roach1
      - redis
      - rabbitmq
      - consul
    networks:
      - chainpoint
    environment:
      NODE_ENV: development
      CHAINPOINT_CORE_BASE_URI: ${CHAINPOINT_CORE_BASE_URI}
      ANCHOR_BTC: ${ANCHOR_BTC}
      ANCHOR_ETH: ${ANCHOR_ETH}
      ETH_TNT_LISTEN_ADDRS: ${ETH_TNT_LISTEN_ADDRS}    
      SIGNING_SECRET_KEY: ${SIGNING_SECRET_KEY}
      VIRTUAL_HOST: api.local
      TENDERMINT: http://tendermint:26657

  api-test:
    container_name: node-api-service-test
    build:
      context: .
      dockerfile: docker/Dockerfile.api-test
    depends_on:
      - base
      - roach1
      - redis
      - rabbitmq
      - consul
    networks:
      - chainpoint
    environment:
      NODE_ENV: test
      CHAINPOINT_CORE_BASE_URI: http://test.chainpoint.org
      ANCHOR_BTC: ${ANCHOR_BTC}
      ANCHOR_ETH: ${ANCHOR_ETH}
      ETH_TNT_LISTEN_ADDRS: ${ETH_TNT_LISTEN_ADDRS}   
      SIGNING_SECRET_KEY: ${SIGNING_SECRET_KEY} 
      VIRTUAL_HOST: api.local


  # NIST Beacon
  # Retrieve and store current NIST Beacon records
  #
  # SCALED: false
  #
  # PORTS : none
  #
  nist-beacon:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.nist-beacon
    container_name: nist-beacon-core
    depends_on:
      - base
    networks:
      - chainpoint
    environment:
      NODE_ENV: development

  # Bitcoin Transmit
  # Send Calendar Block Merkle roots to be embedded in a BTC transaction.
  #
  btc-tx:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.btc-tx
    container_name: btc-tx-core
    depends_on:
      - base
      - roach1
      - rabbitmq
    networks:
      - chainpoint
    environment:
      NODE_ENV: production
      CHAINPOINT_CORE_BASE_URI: ${CHAINPOINT_CORE_BASE_URI}
      INSIGHT_API_BASE_URI: ${INSIGHT_API_BASE_URI}
      BITCOIN_WIF: ${BITCOIN_WIF}
      USE_BTCETH_TESTNET: "true"
      REDIS_CONNECT_URIS: "redis://redis:6379"

  # Bitcoin Transmit MonitorF
  # Monitor and report on the state of BTC transactions this app has submitted.
  #
  btc-mon:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.btc-mon
    container_name: btc-mon-core
    depends_on:
      - base
      - rabbitmq
      - redis
    networks:
      - chainpoint
    environment:
      NODE_ENV: development
      INSIGHT_API_BASE_URI: ${INSIGHT_API_BASE_URI}

  # Proof State
  # Encapsulates all persistent data storage for partial proof data.
  #
  proof-state:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.proof-state
    depends_on:
      - base
      - rabbitmq
      - roach1
      - consul
    networks:
      - chainpoint
    environment:
      NODE_ENV: development
      ANCHOR_BTC: ${ANCHOR_BTC}
      ANCHOR_ETH: ${ANCHOR_ETH}
      CHAINPOINT_CORE_BASE_URI: ${CHAINPOINT_CORE_BASE_URI}

  # Proof Generation
  # Responsible for constructing, signing, and validating Chainpoint proofs
  # for Calendar, Bitcoin, and Ethereum attestation levels.
  #
  proof-gen:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.proof-gen
    volumes:
      - ./data/gcp:/gcp
    depends_on:
      - base
      - rabbitmq
      - roach1
    networks:
      - chainpoint
    environment:
      NODE_ENV: development
      GOOGLE_APPLICATION_CREDENTIALS: /gcp/proof-proxy-544fdab72f21.json

  # RabbitMQ
  #
  # Admin Page (username:pass)
  # http://127.0.0.1:15673/ (rabbitmq:rabbitmq)
  #
  # LOCAL PORTS:
  # amqp : 5673 (+1 over default)
  # http : 15673 (+1 over default)
  #
  rabbitmq:
    restart: always
    image: rabbitmq:3.6.11-management-alpine
    container_name: rabbitmq-core
    hostname: rabbitmq
    ports:
    - 5673:5672
    - 15673:15672
    environment:
      RABBITMQ_DEFAULT_USER: chainpoint
      RABBITMQ_DEFAULT_PASS: chainpoint
    networks:
      - chainpoint

  # Redis
  #
  redis:
    restart: always
    image: redis:4.0.9-alpine
    container_name: redis-core
    ports:
      - "6382:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./data/redis:/data
    networks:
      - chainpoint
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  # Consul
  #
  # Consul Admin UI: http://127.0.0.1:8500
  #
  consul:
    restart: always
    image: consul:1.1.0
    container_name: consul-core
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    volumes:
      - ./data/consul:/consul/data
    networks:
      - chainpoint

  # CockroachDB
  #
  # CockroachDB Admin UI: http://127.0.0.1:8080
  #
  # Enable slow query logging with COCKROACH_TRACE_SQL and:
  #   SET CLUSTER SETTING sql.trace.log_statement_execute = true;
  #
  roach1:
    restart: always
    image: cockroachdb/cockroach:v2.1.2
    container_name: roach1-core
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./data/roach1:/cockroach/cockroach-data:Z
    command:
      - start
      - --insecure
    networks:
      - chainpoint
    environment:
      COCKROACH_TRACE_SQL: "1000ms"


  # Task Handler
  # node-resque job processing queue
  #
  task-handler:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.task-handler
    depends_on:
      - base
      - roach1
      - redis
      - rabbitmq
    networks:
      - chainpoint
    environment:
      NODE_ENV: development
      SIGNING_SECRET_KEY: ${SIGNING_SECRET_KEY}
      DEBUG: "task-handler:*"
      DEBUG_HIDE_DATE: "false"
      # DEBUG_COLORS: "true"
      DEBUG_DEPTH: 10
      DEBUG_SHOW_HIDDEN: "enabled"

  # Task Handler Admin (Resque Web) UI
  # Web UI for task-handler node-resque job processing queue
  # Access locally : http://127.0.0.1:9292/overview
  #
  task-handler-admin:
    restart: always
    image: gcr.io/chainpoint-registry/github-chainpoint-resque-web:729120d93d6565851311d8e82a9c1ebb1bd85b09
    depends_on:
      - base
      - redis
      - task-handler
    networks:
      - chainpoint
    ports:
      - "9292:9292"
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_NAMESPACE: resque
