FROM golang:latest
ENV GOBIN /go/bin
RUN mkdir -p $GOPATH/src/github.com/chainpoint/chainpoint-core/go-abci-service
WORKDIR $GOPATH/src/github.com/chainpoint/chainpoint-core/go-abci-service
ADD ./go-abci-service/ ./
RUN ls
RUN make
RUN make get_vendor_deps
RUN make install