FROM gcr.io/chainpoint-registry/github_chainpoint_chainpoint-core/node-base

COPY node-lib/lib /home/node/app/lib

COPY node-lnd-mon-service/package.json node-lnd-mon-service/yarn.lock /home/node/app/
RUN yarn

COPY node-lnd-mon-service/server.js /home/node/app/
COPY node-api-service/env_secrets_expand.sh /home/node/app
COPY node-api-service/run.sh /home/node/app

CMD ["/bin/bash", "-c", "/home/node/app/run.sh"]