FROM gcr.io/chainpoint-registry/github_chainpoint_chainpoint-core/node-base

COPY node-lib/lib /home/node/app/lib

COPY node-btc-tx-service/package.json node-btc-tx-service/yarn.lock /home/node/app/
RUN yarn

COPY node-btc-tx-service/server.js /home/node/app/
COPY node-btc-tx-service/run.sh /home/node/app/
COPY node-btc-tx-service/env_secrets_expand.sh /home/node/app/

CMD ["./run.sh"]
