logLevel = "DEBUG"
defaultEntryPoints = ["http", "https", "dash", "rpc"]

[web]
    [entryPoints]
        [entryPoints.http]
            address = ":8080"
            [entryPoints.http.forwardedHeaders]
                trustedIPs = ["127.0.0.0/32", "10.0.0.0/32", "192.168.0.0/16"] # some trusted ip which will never match
        [entryPoints.https]
            address = ":8443"
            [entryPoints.https.redirect]
                entryPoint="http"
        [entryPoints.portainer]
            address = ":9000"
        [entryPoints.dash]
            address = ":8081"
        [entryPoints.rpc]
            address=":26657"

[api]
    entrypoint = "dash"
    dashboard = false

[docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    swarmmode = true
    exposedbydefault = false
